[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'Shougo/denite.nvim'
#depends = ['roxma/nvim-yarp', 'roxma/vim-hug-neovim-rpc']
#hook_add = '''
#    autocmd FileType denite call s:denite_my_settings()
#    function! s:denite_my_settings() abort
#        nnoremap <silent><buffer><expr> <CR>
#        \ denite#do_map('do_action')
#        nnoremap <silent><buffer><expr> d
#        \ denite#do_map('do_action', 'delete')
#        nnoremap <silent><buffer><expr> p
#        \ denite#do_map('do_action', 'preview')
#        nnoremap <silent><buffer><expr> <ESC>
#        \ denite#do_map('quit')
#        nnoremap <silent><buffer><expr> i
#        \ denite#do_map('open_filter_buffer')
#        nnoremap <silent><buffer><expr> <Space>
#        \ denite#do_map('toggle_select').'j'
#    endfunction
#
#    nmap [denite] <Nop>
#    map , [denite]
#    nnoremap <silent> [denite]f :<C-u>Denite file buffer file:new<CR>
#'''

#[[plugins]]
#repo = 'roxma/nvim-yarp'

#[[plugins]]
#repo = 'roxma/vim-hug-neovim-rpc'

#[[plugins]]
#repo = 'Shougo/neosnippet.vim'
#hook_add = '''
#    let g:neosnippet#snippets_directory='~/.vim/snippets/'
#'''

#[[plugins]]
#repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    nnoremap <silent><C-e> :NERDTreeToggle<CR>
    let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline_powerline_fonts = 1
'''
depends = ['vim-airline-themes']

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'
